name: Automated Backend Deployment
run-name: ${{ github.actor }} is deploying the updated code to the backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p ~/.ssh
      - name: Save SSH config
        run: echo "${{ secrets.VPS_SSH_CONFIG }}" >> ~/.ssh/config
      - name: Save SSH key
        run: echo "${{ secrets.VPS_SSH_KEY }}" >> ~/.ssh/id
      - name: Set correct permissions for SSH key file
        run: chmod 600 ~/.ssh/id
      - name: Save SSH destination to known_hosts
        run: ssh-keyscan -p ${{ secrets.VPS_SSH_PORT }} ${{ secrets.VPS_IP_ADDRESS }} >> ~/.ssh/known_hosts
      - name: Run commands on VPS
        run: |
          ssh vps-driverless-humans-deploy << 'EOF'
            cd /opt/DriverlessHumans/Driverless-Humans/Backend/
            docker compose down || true
            git fetch origin
            git checkout main
            git reset --hard origin/main
            docker compose up --build -d
          EOF
